# Generated by Django 3.2.20 on 2023-07-23 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelatih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=30)),
                ('alamat', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('telp', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('jenis', models.CharField(max_length=30)),
                ('pelatih', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pelatih')),
            ],
        ),
        migrations.CreateModel(
            name='SertifikatPelatih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(upload_to='upload/images/')),
                ('pelatih', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pelatih')),
            ],
        ),
        migrations.CreateModel(
            name='pengalaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.TextField(max_length=2000)),
                ('foto', models.ImageField(upload_to='upload/images/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('periode', models.CharField(max_length=20)),
                ('tahun', models.CharField(max_length=4)),
                ('nama_pengalaman', models.TextField(max_length=1000)),
                ('pelatih', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pelatih')),
            ],
        ),
        migrations.CreateModel(
            name='KejuaraanPelatih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medali', models.CharField(max_length=1)),
                ('tahun', models.CharField(max_length=4)),
                ('kejuaraan', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('foto', models.ImageField(upload_to='upload/images/')),
                ('pelatih', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pelatih')),
            ],
        ),
        migrations.CreateModel(
            name='jenis_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveIntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('nama_skill', models.CharField(max_length=30)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.skill')),
            ],
        ),
    ]
