# Generated by Django 3.2.20 on 2023-07-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230723_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenis_skill',
            name='skill',
            field=models.CharField(choices=[('1', 'Berenang'), ('2', 'Senam'), ('3', 'Atletik'), ('4', 'Fitness'), ('5', 'Game Team')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='kejuaraanpelatih',
            name='medali',
            field=models.CharField(choices=[('Emas', 'Emas'), ('Perak', 'Perak'), ('Perunggu', 'Perunggu')], default='Emas', max_length=10),
        ),
    ]
