# Generated by Django 3.2.20 on 2023-07-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230723_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='perkembangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kejuaraan', models.BigIntegerField()),
                ('tahun', models.CharField(max_length=4)),
                ('namaBidang', models.CharField(choices=[('Sepak Bola Indonesia', 'Sepak Bola Indonesia'), ('Basket Indonesia', 'Basket Indonesia'), ('Renang Indonesia', 'Renang Indonesia'), ('Badminton Indonesia', 'Badminton Indonesia'), ('Voli Indonesia', 'Voli Indonesia')], max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Perkembangan',
            },
        ),
    ]
